dataset:
  levels: 10
  price_scale: 10000
  tickers:
    - symbol: AAPL
      message_csv: data/raw/LOBSTER_SampleFile_AAPL_2012-06-21_10/AAPL_2012-06-21_34200000_57600000_message_10.csv
      orderbook_csv: data/raw/LOBSTER_SampleFile_AAPL_2012-06-21_10/AAPL_2012-06-21_34200000_57600000_orderbook_10.csv
    - symbol: AMZN
      message_csv: data/raw/LOBSTER_SampleFile_AMZN_2012-06-21_10/AMZN_2012-06-21_34200000_57600000_message_10.csv
      orderbook_csv: data/raw/LOBSTER_SampleFile_AMZN_2012-06-21_10/AMZN_2012-06-21_34200000_57600000_orderbook_10.csv
    - symbol: GOOG
      message_csv: data/raw/LOBSTER_SampleFile_GOOG_2012-06-21_10/GOOG_2012-06-21_34200000_57600000_message_10.csv
      orderbook_csv: data/raw/LOBSTER_SampleFile_GOOG_2012-06-21_10/GOOG_2012-06-21_34200000_57600000_orderbook_10.csv
    - symbol: INTC
      message_csv: data/raw/LOBSTER_SampleFile_INTC_2012-06-21_10/INTC_2012-06-21_34200000_57600000_message_10.csv
      orderbook_csv: data/raw/LOBSTER_SampleFile_INTC_2012-06-21_10/INTC_2012-06-21_34200000_57600000_orderbook_10.csv
    - symbol: MSFT
      message_csv: data/raw/LOBSTER_SampleFile_MSFT_2012-06-21_10/MSFT_2012-06-21_34200000_57600000_message_10.csv
      orderbook_csv: data/raw/LOBSTER_SampleFile_MSFT_2012-06-21_10/MSFT_2012-06-21_34200000_57600000_orderbook_10.csv


labels:
  horizon: 500
  label_mode: binary_drop_ties

features:
  ofi_window_raw: 50
  ofi_norm_windows: [10, 50, 100]
  vol_window: 50
  intensity_window: "1s"

split:
  train_fraction: 0.7

models:
  logistic:
    random_state: 42

  hist_gbdt:
    random_state: 42
    learning_rate: 0.05
    max_iter: 200
    max_leaf_nodes: 31
    min_samples_leaf: 50
    l2_regularization: 0.0